### PR TITLE
Version 0.1

### PR DESCRIPTION
**Pull request by dantop114**
This PR implements a totally new structure for the reporter. The new reports structure can be found in the README.
Also issues #2, #3 , #4 can be closed. Sorry about the poor communication.

## Technical specification
The `pie-reporter` has now a totally new approach. More functional, based on state transitions. A good explanation is given by this diagram:

State Diagram

All the users informations are now stored in a document-oriented database that can be queried using `tinydb` and the python console. Leveraging this new feature we can do queries on the actual user base to get a sense on where we are going. 

This can be seen for example in `reporter.py`:

```python
# fetches all the active users
accounts = db.table("accounts").search(Account.state == AccountState.ACTIVE.value)
```

### Reports
Reports now contains the minimal informations to compute the state. All the reports are in a CSV format to avoid confusion.

### CODE REVIEW

**Comment by AdrianAddesso** [comment]
@dantop114  some feedback:

**Please consider adding this information next to each state**
**Active:** user voted this month. (Accrue+Claim)
**Inactive:** user did not vote this month. (Accrue+Can't Claim)
**Slashed:** user did not vote for 3 consecutive epochs (1 epoch = 1 calendar month). (Slahed+Can't Claim)

**Slashed -> Inactive (5)**
1. please change (a) to read: 'redistribute his unclaimed rewards...'

**Slashed -> Inactive (5)**
1. Arrow is going to active, which is not the case explained
2. Shouldn't we do Path 4, action b and c?

**Slashed -> Inactive (6)**
1. Arrow is going to inactive, which is not the case explained

**Comment by dantop114** [comment]
> @dantop114 some feedback:
> 
> **Please consider adding this information next to each state** **Active:** user voted this month. (Accrue+Claim) **Inactive:** user did not vote this month. (Accrue+Can't Claim) **Slashed:** user did not vote for 3 consecutive epochs (1 epoch = 1 calendar month). (Slahed+Can't Claim)
> 
> **Slashed -> Inactive (5)**
> 
> 1. please change (a) to read: 'redistribute his unclaimed rewards...'
> 
> **Slashed -> Inactive (5)**
> 
> 1. Arrow is going to active, which is not the case explained
> 2. Shouldn't we do Path 4, action b and c?
> 
> **Slashed -> Inactive (6)**
> 
> 1. Arrow is going to inactive, which is not the case explained

Case 6 should be *Slashed -> Slashed* (if someone does not vote for 4 months, he's still slashed and not getting any reward).
Updated the diagram according to this.

**Comment by AdrianAddesso** [comment]
@dantop114  minor adjustment
**Slashed -> Active** & **Slashed -> Slashed** have the same numerical reference = 6

Also, I still believe that clarifying * (1 epoch = 1 calendar month)* is worth when defining the status at the top, as even though during the descriptions we mention Months to facilitate understanding, the notarization will be done through epochs 
> Slashed: user did not vote for 3 consecutive epochs (1 epoch = 1 calendar month). (Slahed+Can't Claim)

**Comment by AdrianAddesso** [comment]
@dantop114  regarding the reports, they look ok to me. One question though, and just need to ask you to confirm the description of each report below is accurate enough:

**General**
- **Claims.json:** Addresses that claimed their rewards during the report Epoch.
- **Epoch.conf.json:** star-end time of the Epoch of the report

**JSON files**
- **Distribution:** Distributed amount per address
- **Rewards:** Amount of rewards entitled for the current Epoch
- **Stakers:** Addresses and their current balance **(is this pre o post distribution?)** <------ pls check

**CSV**
- **Distribution:** same as JSON, Distributed amount per address
- **Non_Voters:** Addressed that did not vote on the reported Epoch
- **Proposals:** List of eligible proposals
- **Rewards:**  same as JSON, Amount of rewards entitled for the current Epoch
- **Stakers:**  same as JSON, Addresses and their current balance **(is this pre o post distribution?)** <------ pls check
- **Voters:** Addresses that voted on the reported Epoch
- **Votes:** Address vote history per proposal

**Comment by dantop114** [comment]
> * **Stakers:** Addresses and their current balance **(is this pre o post distribution?)** <------ pls check

What do you mean? That is the veDOUGH balance, so it has no dependency with distribution.

**Pull request merged**
